trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
#- task: UsePythonVersion@0
#  inputs:
#    versionSpec: '3.x'
#    addToPath: true

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    goals: 'clean test'

#- task: PublishTestResults@2
#  inputs:
#    testResultsFiles: '**/surefire-reports/TEST-*.xml'
#    testRunTitle: 'Automated Test Results'

- script: |
    mkdir -p $(Build.ArtifactStagingDirectory)/test-reports
    cp -R $(Agent.TempDirectory)/surefire-reports $(Build.ArtifactStagingDirectory)/test-reports
  displayName: 'Copy Maven test reports to artifacts'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)/target'
    artifact: 'drop'
    publishLocation: 'Container'
